export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  KYC_UPDATE = 'KYC_UPDATE',
}
